# Generated by Django 5.0.2 on 2024-02-18 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteSharedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='notes.note')),
                ('shared_users', models.ManyToManyField(blank=True, related_name='shared_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
