# Generated by Django 5.0.2 on 2024-02-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_noteversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteversion',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED')], default='CREATED', max_length=16),
            preserve_default=False,
        ),
    ]
